# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac900a78a8b87d1a81905460b287e22ca1a77e23174c9c167be0cc9a14a382dbe21ad04c07783225022c8cfe6860ad3d735bbee1bd0a24d09a304294b2223fd

test:
  secret_key_base: cf8ae350e06f0eeda873865bba181912669fe2d4cf705d49fba803c8811eceaf6631febbd6d0cc13e8d2d90e3f0dd4105f633ba78e132a84e4803451280bbb46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
